-- Script de Criação do Banco de Dados para Clean Foods no Supabase
-- Execute este script no SQL Editor do painel do seu projeto Supabase.

-- =========================================================================
-- 1. TABELA DE CATEGORIAS
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir leitura pública de categorias" 
ON public.categories FOR SELECT 
USING (true);

CREATE POLICY "Permitir controle total de categorias por administradores autenticados" 
ON public.categories FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- 2. TABELA DE PRODUTOS
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.products (
    id bigint PRIMARY KEY, -- ID controlado pelo React/Date.now()
    name text NOT NULL,
    description text,
    price numeric NOT NULL,
    "promoPrice" numeric,
    category text REFERENCES public.categories(name) ON UPDATE CASCADE ON DELETE SET NULL,
    image text,
    available boolean DEFAULT true NOT NULL,
    "chefTip" boolean DEFAULT false NOT NULL,
    ingredients text,
    calories text,
    carbs text,
    proteins text,
    "totalFats" text,
    "saturatedFats" text,
    "transFats" text,
    fiber text,
    sodium text,
    "pricedByGrams" boolean DEFAULT false NOT NULL,
    "weightBasis" integer DEFAULT 100,
    "weightOptions" jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir leitura pública de produtos" 
ON public.products FOR SELECT 
USING (true);

CREATE POLICY "Permitir controle total de produtos por administradores autenticados" 
ON public.products FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- 3. TABELA DE CONFIGURAÇÕES DA LOJA
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.store_settings (
    id bigint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    "storeName" text NOT NULL,
    "heroTitle" text NOT NULL,
    "heroSubtitle" text NOT NULL,
    "deliveryFee" numeric DEFAULT 0 NOT NULL,
    "whatsappNumber" text NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir leitura pública de configurações" 
ON public.store_settings FOR SELECT 
USING (true);

CREATE POLICY "Permitir controle total de configurações por administradores autenticados" 
ON public.store_settings FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- 4. TABELA DE CUPONS DE DESCONTO
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.coupons (
    id bigint PRIMARY KEY, -- ID controlado pelo React/Date.now()
    code text NOT NULL UNIQUE,
    description text,
    percentage numeric NOT NULL,
    scope text DEFAULT 'all'::text NOT NULL,
    "productIds" jsonb DEFAULT '[]'::jsonb NOT NULL,
    active boolean DEFAULT true NOT NULL,
    weekdays jsonb DEFAULT '[0,1,2,3,4,5,6]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir leitura pública de cupons" 
ON public.coupons FOR SELECT 
USING (true);

CREATE POLICY "Permitir controle total de cupons por administradores autenticados" 
ON public.coupons FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- 5. TABELA DE PEDIDOS
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY, -- ID alfanumérico do cliente (ex: CF-9843)
    date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    customer jsonb NOT NULL,
    items jsonb NOT NULL,
    "deliveryFee" numeric DEFAULT 0 NOT NULL,
    coupon jsonb,
    total numeric NOT NULL,
    status text DEFAULT 'Pendente'::text NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir inserção pública de pedidos" 
ON public.orders FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir controle total de pedidos por administradores autenticados" 
ON public.orders FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
